# Reshaping Arrays

In [2]:
import numpy as np
new_data = np.array([1, 2, 3, 4, 5, 6])

In [9]:
x = new_data.reshape(2,3)

In [10]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
y = new_data.reshape(3,2)
y

array([[1, 2],
       [3, 4],
       [5, 6]])

In [17]:
z = np.ones((2,3))
z

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
x - z

array([[0., 1., 2.],
       [3., 4., 5.]])

In [29]:
4*(x - z)  #scalar multiplication

array([[ 0.,  4.,  8.],
       [12., 16., 20.]])

# creating Multi- Dimentional Array

In [21]:
 a = np.array([[[10, 20], [3, 40]], [[50, 60], [70,80]]])

In [22]:
a

array([[[10, 20],
        [ 3, 40]],

       [[50, 60],
        [70, 80]]])

In [24]:
 np.ones((5, 3, 3)) #create 5 arrays of 3row and 3 columns

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [27]:
np.random.random((5,3,2))   #create  5 array sets of random nums, with 3 rows and 2 columns each

array([[[0.5466922 , 0.03867806],
        [0.47281466, 0.35657432],
        [0.49821795, 0.45838983]],

       [[0.93900463, 0.49328839],
        [0.45040398, 0.59070396],
        [0.50457458, 0.82774934]],

       [[0.74618846, 0.9394156 ],
        [0.76895743, 0.58220405],
        [0.73854199, 0.1108382 ]],

       [[0.19244008, 0.16641415],
        [0.98696857, 0.39796262],
        [0.96791276, 0.10622305]],

       [[0.83544848, 0.99424835],
        [0.7778309 , 0.32544547],
        [0.71789377, 0.27838918]]])

In [28]:
np.zeros((4,5,1))   #create 4 arrays of zero elements, 5 rows and a column each

array([[[0.],
        [0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.],
        [0.]]])

In [31]:
type(np.zeros((4,5,1)) )

numpy.ndarray