In [1]:
import numpy as np

In [2]:
np.random.random(5)  #to generate random floating point array of numbers between 0 and 1

array([0.32302322, 0.61235256, 0.66524322, 0.17864802, 0.70876174])

In [3]:
np.ones(5) #display elements of 1 in 5 places

array([1., 1., 1., 1., 1.])

In [4]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
new_maths = np.array([1, 2, 3])
new_ones =np.ones(3)

In [7]:
new_maths + new_ones

array([1., 2., 3.])

In [8]:
new_maths - new_ones

array([0., 1., 2.])

In [9]:
new_maths * new_ones

array([1., 2., 3.])

In [13]:
np.round(new_ones / new_maths, 3) 

array([1.   , 0.5  , 0.333])

In [14]:
new_maths * 2

array([2, 4, 6])

In [15]:
new_maths[0]

1

In [16]:
new_maths[-2]

2

# Math Functions with 1-D Array

In [18]:
new_maths.max() #to obtain the maximum number

3

In [20]:
new_maths.min() #to obtain the minimum number in the array

1

In [22]:
new_maths.sum() #to obtain the sum of all the numbers in the array

6

In [23]:
np.mean(new_maths)

2.0

In [25]:
np.median(new_maths)

2.0

# Creating N-D Arrays or Matrices

In [30]:
x = np.array([[10, 20], [30, 40]])    # to produce 2 dim Array

In [31]:
x

array([[10, 20],
       [30, 40]])

In [37]:
np.ones((3, 4))           #multi dim Array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [34]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [44]:
first_arr = np.random.random((3,4)) #multi Dim Array of random numbers

In [45]:
first_arr

array([[0.44290405, 0.81316153, 0.52997348, 0.56830343],
       [0.5530752 , 0.09099656, 0.96650715, 0.30489422],
       [0.80581026, 0.31434301, 0.21730952, 0.18335278]])

In [46]:
second_arr = np.random.randint(4,6)

In [47]:
first_arr * second_arr   

array([[1.77161621, 3.2526461 , 2.11989393, 2.27321371],
       [2.21230079, 0.36398622, 3.86602859, 1.21957687],
       [3.22324105, 1.25737206, 0.86923807, 0.73341113]])

It is very impractical to use be do arithemetics on 2 random operands,
because their values will keep changing each time you run the cell 

# Doing  Math Operation with N-D Arrays

In [48]:
y = np.array([[2,4], [5,6]])

In [50]:
x + y    #for operations to run the arrays must be of same dim

array([[12, 24],
       [35, 46]])

In [51]:
x.dot(y)

array([[120, 160],
       [260, 360]])

In [52]:
 y.max()

6

In [53]:
y.min()

2

## Indexing For Matrices

Indexing simply means the technique used in accessing values in an array

In [55]:
y[0, 1]  #carinal position of a value

4

In [56]:
 y[1,1]

6

In [57]:
x[0,0]

10

In [58]:
y[1,0]

5

In [60]:
#if we want to access a range of values in an array, you can use slicing techniques

In [61]:
y[0:2, 1]

array([4, 6])

In [62]:
y[0:1, 1]

array([4])